# Generated by Django 3.1.5 on 2021-01-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='media/123.png', upload_to='media/%Y/%m/%d')),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255)),
                ('configuration', models.URLField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid_by', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('used_by', models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_device.workers')),
            ],
        ),
    ]
